### ISSUE TITLE
App Functionality

### ISSUE THREAD

**Issue by cahhansen** [UtahHydroinformatics/TeamEdwardClimate#1]
All the data files have to be loaded in a data folder in order to run on others' computers (instead of just put in the project directory) because that's how your app references them.

Also, don't forget to load the 'jpeg' package in the global.R file or the pictures won't display when the app is hosted or ran on someone else's computer!

**Comment by bterry23** [comment]
Thanks for the heads up Carly!  Data folder has been added to repository along with jpeg package in global script.
